config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  root 'users/homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    get 'homes/top'
    get 'homes/about'
    get 'users/cancel'

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'like'
        get 'confirm'
        get 'search'
        put "/users/:id/hide" => "users#hide", as: 'hide'
      end
    end

    resources :posts do
      collection do
        get 'search'
      end
      resources :comments, only: [:create, :destroy]
    end

    resources :events
  end

  scope module: :users do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get 'like'
        get 'confirm'
        get 'cancel_confirmation'
        get 'edit_password'
        put 'edit_password'
        put "/users/:id/hide" => "users#hide", as: 'hide'
      end
    end

    resources :posts do
      collection do
        get 'search'
        get 'prefecture'
      end
      resources :comments, only: [:create, :destroy]
    end

    resources :events, only: [:index, :show]
    get 'likes/index'
    post   '/like/:post_id' => 'likes#like',   as: 'like'
    delete '/like/:post_id' => 'likes#unlike', as: 'unlike'

    get 'homes/top'
    get 'homes/about'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # liked_postsによってuserがどの投稿をいいねしているのかを簡単に取得できる
  has_many :like_posts, through: :likes, source: :post
  attachment :profile_image

  # 退会済みのユーザーはログインできなくする
  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :introduction, { length: { maximum: 80 } }
  validates :name, { presence: true, length: { in: 2..20 } }

  def self.search(search)
    search
    User.where(['name LIKE ? OR email LIKE ?', "%#{search}%", "%#{search}%"])
  end

  enum prefecture: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47,
  }

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @events = Event.all
  end

  def about
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def like
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: :published) # .published.order("created_at DESC").page(params[:page]).per(10)
  end

  def confirm
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: :draft) # .draft.order("created_at DESC")
    end

  def edit
    @user = User.find(params[:id])
    @user = User.find_by(params[:user_id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def hide
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    flash[:notice] = "退会処理が完了しました。"
    redirect_to admins_users_path
  end

  def search
    @users = User.search(params[:search])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      @comment = Comment.new
    else
      @comment = Comment.new
      redirect_back(fallback_location: root_path)
     end
 end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.user != current_user
      # リダイレクト先考える
      redirect_to request.referer
    else
      @comment.destroy
      @new_comment = Comment.new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :parent_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/events_controller.rb
class Users::EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @post = Post.where(event_id: params[:id])
    @lat = @event.latitude
    @lng = @event.longitude
    gon.lat = @lat
    gon.lng = @lng
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
    @posts = Post.limit(3).sort { |a, b| b.liking_users.count <=> a.liking_users.count } # 投稿のいいね数を比較して降順で表示
    @events = Event.all
    @user = current_user
    if user_signed_in?
      @topic_event = Event.where(prefecture: @user.prefecture)#ユーザーが登録した都道府県のeventを配列で探す
      @user_prefecture_posts = Post.where(prefecture: @user.prefecture)
    else
    end
  end

  def about
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
    @lat = 35.706090265070664
    @lng = 139.8695789931152
  end

  def index
    @posts = Post.all
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @lat = @post.latitude
    @lng = @post.longitude
    gon.lat = @lat
    gon.lng = @lng
  end

  def create
    # Eventテーブルのfestival、prefectureを配列で探してきている
    @event = Event.where(festival: params[:post][:festival], prefecture: params[:post][:prefecture])
    @post = Post.new(post_params)
    @post.latitude = params["latitude"]
    @post.longitude = params["longitude"]
    @post.user_id = current_user.id
    # festival、prefectureが一致するものがあったらその配列の0番目をとってくる
    if @event.length > 0
      @post.event_id = @event[0].id
    end
    @user = current_user
    if @post.save
      # リダイレクト先変える
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @lat = @post.latitude
    @lng = @post.longitude
    if @post.user == current_user
       render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post.latitude = params["latitude"]
    @post.longitude = params["longitude"]
    if @post.update(post_params)
      # flash[:notice] = "You have updated post successfully."
      redirect_to post_path(@post.id)
    else
      render :edit
    end
   end

  def destroy
    @post.destroy
    redirect_to user_path(current_user)
  end

  def search
    @posts = Post.search(params[:search])
  end

  def prefecture
    @posts = Post.where(prefecture: params[:prefecture])
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:festival, :prefecture, :city, :transportation, :status, :impressions, :image, :date, :belongings, :rate, :user_id, :addres, :latitude, :longitude)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def like
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: :published) # .published.order("created_at DESC").page(params[:page]).per(10)
  end

  def confirm
    @user = current_user
    @posts = @user.posts.where(status: :draft) # .draft.order("created_at DESC")
    end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def edit_password
    @user = current_user
  end

  def cancel_confirmation
    @user = current_user
  end

  # def destroy
  #     @user = User.find(params[:id])
  #     @user.destroy
  #     flash[:success] = 'ご利用ありがとうございました'
  #     redirect_to :root
  # end

  def hide
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :prefecture)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/homes/_japan_map.html.erb
<script>
        $(function(){
            var areas = [
                {code : 1, name: "北海道地方", color: "#7f7eda", hoverColor: "#b3b2ee", prefectures: [1]},
                {code : 2, name: "東北地方",   color: "#759ef4", hoverColor: "#98b9ff", prefectures: [2,3,4,5,6,7]},
                {code : 3, name: "関東地方",   color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [8,9,10,11,12,13,14]},
                {code : 4, name: "中部地方",   color: "#7cdc92", hoverColor: "#aceebb", prefectures: [15,16,17,18,19,20,21,22,23]},
                {code : 5, name: "近畿地方",   color: "#ffe966", hoverColor: "#fff19c", prefectures: [24,25,26,27,28,29,30]},
                {code : 6, name: "中国地方",   color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [31,32,33,34,35]},
                {code : 7, name: "四国地方",   color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [36,37,38,39]},
                {code : 8, name: "九州地方",   color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [40,41,42,43,44,45,46]},
                {code : 9, name: "沖縄地方",   color: "#eb98ff", hoverColor: "#f5c9ff", prefectures: [47]},
            ];

            $("#map-container").japanMap({
                width: 800,
                selection: "prefectures",
                areas: areas,
                backgroundColor : "#fff",
                borderLineColor: "#f2fcff",
                borderLineWidth : 0.25,
                lineColor : "#fff",
                lineWidth: 1,
                drawsBoxLine: true,
                showsPrefectureName: true,
                prefectureNameType: "short",
                movesIslands : true,
                fontSize : 11,
                fontShadowColor : "none",
                fontColor : "#585858",
                onSelect : function(data){
                  window.location.href = `<%= prefecture_posts_path %>` + `?prefecture=${data.code}`
                }
            });
        });
</script>

<div id="map-container"></div>

app/views/users/homes/about.html.erb
<!------ スライドショー ------>
<div class="slideshow-box">
   <p id="slideshow">
      <%= image_tag(asset_path('sunset1.jpg'), alt: "画像1", class: "active") %>
      <%= image_tag(asset_path('sunset2.jpg'), alt: "画像2") %>
      <%= image_tag(asset_path('sunset3.jpg'), alt: "画像3") %>
      <%= image_tag(asset_path('sunset4.jpg'), alt: "画像4", id: "last_image") %>
   </p>
   <p class="about-title">SPOT HANABI</p>
</div>

   <script type="text/javascript">
       var intervalId = null;
       var counter = 0;
   function slideSwitch() {
      var $active = $('#slideshow img.active');

      if ( $active.length == 0 ) $active = $('#slideshow img:last');

      var $next =  $active.next().length ? $active.next()
         : $('#slideshow img:first');

      $active.addClass('last-active');

      $next.css({opacity: 0.0})
         .addClass('active')
         .animate({opacity: 1.0}, 3000, function() {
              $active.removeClass('active last-active');
         });

       // var last_img = document.getDocumentById('last_img')
       // if (window.getComputedStyle(last_img).getPropertyValue("opacity") == 1.0) {
       //    clearInterval(intervalId);
       // }
      if (counter++ >= 2) {
         clearInterval(intervalId);
      }
   }

   $(function() {
      intervalId = setInterval( "slideSwitch()", 4000 );
   });
   </script>
   


<div class="about-box">
   <div class="about-content">
      <h4 class="about-index">SPOT HANABIへようこそ</h4>
         <p class="about-text">日本の夏にはかかせない夜空を彩る打ち上げ花火<br>
            SPOT HANABIでは花火大会の感想,おすすめの行き方,持ち物<br>
            よく見えるおすすめSPOTを共有することができます<br>
         </p>
   </div>

   <div class="about-content">
      <h4 class="about-index">SPOT HANABIのたのしみ方</h4>
         <p class="about-text">花火大会に行った感想や情報を投稿できます<br>
            書き途中の投稿は下書きに保存することができます
         </p>

         <p>気に入った投稿はハートアイコンをクリックして<br>
            お気に入りに追加できます<br>
            また今までもらったいいねの数がマイページに表示されます
         </p>
   </div>

   <div class="about-content">
      <h4 class="about-index">カレンダーからさがす</h4>
         <p class="about-text">ユーザーの投稿はカレンダーからも探すことができます</p>
            カレンダーからは今年の花火大会の開催日時も確認できます<br>
         <%= link_to "カレンダーから探す",homes_top_path(anchor: 'calendar-anc'),class: "about-link", class: "btn btn-outline-secondary btn-sm", data: {"turbolinks" => false}%>
   </div>

   <div class="about-content">
      <h4 class="about-index">都道府県から探す</h4><br>
         <%= link_to "都道府県から探すへ",homes_top_path(anchor: 'map-box'),class: "about-link", class: "btn btn-outline-secondary btn-sm", data: {"turbolinks" => false}%>
   </div>

   <div class="about-content">
         <p>新規ユーザー登録をしなくても閲覧は可能ですが<br>
            投稿、コメント、お気に入り登録には会員登録が必要です<br>
         （かんたんログイン（テストユーザー）をぜひご利用ください）</p>
         <%= link_to "TOPへ", root_path,class: "about-link", class: "btn btn-outline-secondary btn-sm", data: {"turbolinks" => false}%>
   </div>
</div>

app/views/users/homes/top.html.erb
<!------ スライド ------>
<div class="top-slide-group">
  <div class="top-slide"><%= image_tag(asset_path('show1.jpg'), alt: "画像1", class: "top-image") %></div>
  <div class="top-slide"><%= image_tag(asset_path('show2.jpg'), alt: "画像1", class: "top-image") %></div>
  <div class="top-slide"><%= image_tag(asset_path('show3.jpg'), alt: "画像1", class: "top-image") %></div>
</div>

<script type="text/javascript">
 $(function() {
    $('.top-slide-group').slick({
        dots: true,
        autoplay: true,
        centerMode: true,
        centerPadding: '15%',
        autoplaySpeed: 3000,
        speed:1500,
    });
});
</script>

<!------ 都道府県別ランキング ------>
<% if user_signed_in? %>
<h4 class="top-index"><%= @user.prefecture %>のおすすめ</h4>
  <div class="row">
    <%= render partial: 'users/posts/index',locals: { posts: @user_prefecture_posts } %>
  </div>
  <% else %>
  <% end %>


<!------ お気に入り数ランキング ------>
<h4 class="top-index">お気に入りランキング</h4>
　<div class="row">
    <%= render partial: 'users/posts/index',locals: { posts: @posts } %>
  </div>

<!------ カレンダー ------>
<h4 class="top-index">カレンダーから探す</h4>
  <div id="calendar-anc">
     <div class="row-xs-12">
          <div class="calendar col-xs-12">
            <%= month_calendar events: @events do |date, events| %>
      	      <%= date.day %>
      	      <% events.each do |event| %>
      		    <div>
      		      <%= link_to event.festival, event_path(event),class: "calendar-link-style", data: {"turbolinks" => false} %>
      		    </div>
                <% end %>
            <% end %>
          </div>
      </div>
  </div>

<!----- クリッカブルマップ ------>
<h4 class="top-index" id="map-box" >都道府県から探す</h4>
<div class="row">
<%= render partial: 'japan_map' %>
</div>