config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  root 'users/homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    get 'homes/top'
    get 'homes/about'
    get 'users/cancel'

    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'like'
        get 'confirm'
        get 'search'
        put "/users/:id/hide" => "users#hide", as: 'hide'
      end
    end

    resources :posts do
      collection do
        get 'search'
      end
      resources :comments, only: [:create, :destroy]
    end

    resources :events
  end

  scope module: :users do
    resources :users, only: [:show, :edit, :update] do
      collection do
        get 'like'
        get 'confirm'
        get 'cancel_confirmation'
        get 'edit_password'
        put 'edit_password'
        put "/users/:id/hide" => "users#hide", as: 'hide'
      end
    end

    resources :posts do
      collection do
        get 'search'
        get 'prefecture'
      end
      resources :comments, only: [:create, :destroy]
    end

    resources :events, only: [:index, :show]
    get 'likes/index'
    post   '/like/:post_id' => 'likes#like',   as: 'like'
    delete '/like/:post_id' => 'likes#unlike', as: 'unlike'

    get 'homes/top'
    get 'homes/about'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { in: 1..300 }
  # コメントを新着順に表示
  default_scope -> { order(created_at: :desc) }
end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    @new_comment = Comment.new
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :parent_id)
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      @comment = Comment.new
    else
      @comment = Comment.new
      redirect_back(fallback_location: root_path)
     end
 end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.user != current_user
      # リダイレクト先考える
      redirect_to request.referer
    else
      @comment.destroy
      @new_comment = Comment.new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admins/comments/_index.html.erb
<!-- コメント一覧 -->
<div>コメント<%= comments.count %>件</div>
    <% comments.each do |comment| %>
      <div>
        <%= link_to user_path(comment.user) do %>
            <%= attachment_image_tag comment.user, :profile_image, format: 'jpeg', size:'50x50', fallback: "no-image.jpg", class: "img-circle" %>
            <%= comment.user.name %>
        <% end %>
        <%= comment.content %>
        <%= comment.created_at %>
        <%= link_to '削除する', admins_post_comment_path(comment.post_id, comment.id), method: :delete, remote: true,class: "btn btn-outline-secondary btn-sm"  %>
      </div>
    <% end %>

app/views/admins/comments/create.js.erb
$("textarea").val("");
$("#comments_area").html("<%= j(render 'index', comments: @post.comments, post: @post, comment: @comment ) %>");

app/views/admins/comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'index', comments: @post.comments, post: @post, comment: @comment ) %>")